export { default as Indexed } from "./Indexed.vue"
export { default as Shop } from "./Shop.vue"
export { default as Checkout } from "./Checkout.vue"
export { default as SingleProduct } from "./SingleProduct.vue"
export { default as NotFound } from "./NotFound.vue"
